#!/usr/bin/env python3
"""Regenerate src/emoji-data.ts.

Sources (both local, no network):
  * CLDR emoji names  — Quartz's quartz/util/emojimap.json (codePointToName)
  * search keywords   — the `emojilib` npm package's emojis.json
Point NAMES/LIB at your own copies if these move.
"""
import json, re, sys

NAMES = sys.argv[1] if len(sys.argv) > 1 else '/Users/joshuahutt/Projects/quartz/quartz/util/emojimap.json'
LIB = sys.argv[2] if len(sys.argv) > 2 else '/Users/joshuahutt/Projects/sigma.js/node_modules/emojilib/emojis.json'

names = json.load(open(NAMES))['codePointToName']
lib = json.load(open(LIB))

SKIN = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}
kw = {}
for short, v in lib.items():
    ch = v.get('char')
    if not ch:
        continue
    words = {w.lower() for w in v.get('keywords', []) if w.isascii()}
    words.add(short.replace('_', ' '))
    kw.setdefault(ch, set()).update(words)

out, seen = [], set()
for cps, name in names.items():
    parts = [int(c, 16) for c in cps.split('-')]
    if any(p in SKIN for p in parts):  # skin-tone variants: the base carries the meaning
        continue
    ch = ''.join(chr(p) for p in parts)
    if ch in seen:
        continue
    seen.add(ch)
    # Emit codepoints as hex, not literal emoji: the blob stays pure ASCII, which
    # roughly thirds its size once the bookmarklet percent-encodes the bundle.
    hexcp = '-'.join(f'{p:x}' for p in parts)
    name = name.lower()
    have = set(re.findall(r'[a-z0-9]+', name))
    extra = sorted(w for w in kw.get(ch, ()) if w and not set(re.findall(r'[a-z0-9]+', w)) <= have)
    out.append(hexcp + '\t' + name + ('\t' + ' '.join(extra) if extra else ''))

blob = '\n'.join(out)
esc = blob.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${').replace('\t', '\\t').replace('\n', '\\n')
open('src/emoji-data.ts', 'w').write(
    '// Generated by tools/gen-emoji.py — do not edit by hand.\n'
    '// The full CLDR emoji set (skin-tone variants folded into their base), packed\n'
    '// as one string of "codepoints<TAB>name<TAB>extra keywords" lines and split at\n'
    f'// runtime. A string this shape costs far less in the bundle than {len(out)} array\n'
    '// literals, which matters most for the bookmarklet — the whole thing rides in a URL.\n'
    f'export const EMOJI_BLOB = `{esc}`\n')
print(f'{len(out)} emoji, {len(blob.encode())} bytes')
